services:
  app:
    image: viettrann/fundamental
    user: "${UID}:${GID}"
    network_mode: "host"
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    network_mode: "host"
    ulimits:
      memlock: -1
    command: >
      --maxmemory=2gb 
      --cache_mode=true 
      --log_dir="/var/log/dragonfly"
    ports:
      - "6379:6379"
    restart: unless-stopped
