name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

jobs:
  check-stable:
    name: Check stable on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check
        run: cargo check --workspace --all-features --all-targets

  style:
    needs: check-stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt
        run: cargo fmt --all --check

  tests:
    needs: check-stable
    name: Test ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        rust: [stable, beta, nightly]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchains: ${{ matrix.rust }}
      - name: Run tests
        run: cargo test --verbose -- --nocapture

  build-docker-images:
    needs: tests
    name: Build Docker image
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Build image in both architectures
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fundamental:latest
          cache-from: type=gha,scope=docker-build
          cache-to: type=gha,scope=docker-build,mode=max
